version: '3.8'
services:
  chat-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: chat_db_user
      POSTGRES_PASSWORD: chat_db_password
      POSTGRES_DB: chat_db
    ports:
      - 5433:5432