name: Dr Pong Chat Server CI

on:
  push:
    branches:
      - /^\d+-.*$/
  pull_request:
    branches:
      - main
jobs:
  CI:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_USER: chat_db_user
          POSTGRES_PASSWORD: chat_db_password
          POSTGRES_DB: chat_db
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      # Set up Node.js
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      # clean install
      - run: npm install

      # build
      - run: npm run build --if-present

      # Start the database service
      - name: Start database service
        run: docker-compose up -d db

      # Wait for the database service to start
      - name: Wait for database service
        run: docker-compose exec db bash -c "while ! nc -z localhost 5432; do sleep 1; done"

      # # Run database migrations (if applicable)
      # - name: Run database migrations
      #   run: npm run db:migrate

      # Run tests
      - name: Run tests
        run: npm test
